name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Running the tests now
        run: |
          cd RestfulBookerTests && dotnet build && dotnet test --logger "html"

      - name: Publish results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: RestfulBookerTests/TestResults
          retention-days: 7
